name = "gcourier"
version = "0.5.0"
description = "Send emails with Gleam."
licences = ["MIT"]
repository = { type = "github", user = "gideongrinberg", repo = "gcourier" }
target = "erlang"
# links = [{ title = "Website", href = "" }]

# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.59.0 and < 1.0.0"
gleam_time = ">= 1.2.0 and < 2.0.0"
gleam_erlang = ">= 0.34.0 and < 1.0.0"
shellout = ">= 1.7.0 and < 2.0.0"
gleam_http = ">= 4.0.0 and < 5.0.0"
gleam_hackney = ">= 1.3.1 and < 2.0.0"
mug = ">= 1.2.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
